package subsistema.pdf.utils.settings;

public enum  StyleEnum {

    DATA_NORMAL,
    INFO_NORMAL,
    SUBTITLE_BOLD,
    DATA_BOLD,
    INFO_BOLD,
    DATA_NORMAL_SPACED,
    SMALL_NORMAL,
    DATA_BOLD_SPACED,
    DATA_SEMI_SPACED,
    MINIMAL_NORMAL,
    MINIMAL_BOLD,
    MINIMAL_NORMAL_SPACED,
    MINIMAL_BOLD_SPACED,
    TABLE_BOLD_SPACED,
    TABLE_MINIMAL_NORMAL_SPACED,
    TABLE_MINIMAL_NORMAL_EXTRA_SPACED,
    TABLE_MINIMAL_BOLD,
    TABLE_MINIMAL_BOLD_EXTRA_SPACED,
    TABLE_MINIMAL_BOLD_EXTRA_SPACED_RED;
}
